### ISSUE TITLE
Initial Launch Fails with Exceptions

### ISSUE THREAD

**Issue by SethFalco** [PhantomBot/PhantomBot#2442]
PhantomBot Version: 3.4.1 (stable) (Revision: 6d1a942)
Operating System: Linux
Java Version: 11.0.4+10-LTS

Detailed Description:

I attempted to launch PhantomBot using the following configuration with Docker Compose:
```yml
version: "3.8"
services:
  phantombot:
    image: gmt2001/phantombot-stable:3.4.1
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - ./PhantomBot_data:/opt/PhantomBot_data
    environment:
      PHANTOMBOT_USER: "bluepandaphantom"
      PHANTOMBOT_OAUTH: "{REDACTED}"
      PHANTOMBOT_CHANNEL: "jenthebluepanda"
      PHANTOMBOT_PANELUSER: "{REDACTED}"
      PHANTOMBOT_PANELPASSWORD: "{REDACTED}"
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_DEBUGON: "true"
```

It seems that a new setup of PhantomBot fails to load because it's unable to write to the locations:

* `./logs/core-error/03-02-2021.txt` (because `./logs/` and `./logs/core-error/` didn't exist)
* `./config/phantombot.db` (because `./config/` didn't exist)

After manually creating those directories, PhantomBot successfully created any other necessary directories automatically, and successfully launched.

Steps to Reproduce:
1) Create a `docker-compose.yml` file similar to mine, ensure it's a fresh launch so there is no prior PhantomBot_data.
2) Run `docker-compose up`
3) Observe exceptions

Logs:
https://gist.github.com/SethFalco/cc6e2a94c869eb0fb5222dd9dba33806
