### ISSUE TITLE
If User Specified but not OAuth, Unhelpful Output

### ISSUE THREAD

**Issue by SethFalco** [PhantomBot/PhantomBot#2443]
PhantomBot Version: 3.4.1 (stable) (Revision: 6d1a942)
Operating System: Linux
Java Version: 11.0.4+10-LTS

Detailed Description:
While setting up PhantomBot, I made the mistake of setting `PHANTOMBOT_USER`, but not `PHANTOMBOT_OAUTH` as I didn't realize that was required.

However, while this was the case, the output of PhantomBot was unhelpful in resolving the problem and even mislead me in solving it.

The output:
`1. Please enter the bot's Twitch username: [02-03-2021 @ 13:16:05.131 GMT] [ERROR] Failed to setup PhantomBot.`

This gave me the impression that it was failing to find the username entirely, while a username was found.
If a username is provided, but not the oAuth token, could it also warn the user that the oAuth token?

Steps to Reproduce:
```yml
version: "3.8"
services:
  phantombot:
    image: gmt2001/phantombot-stable:3.4.1
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - ./PhantomBot_data:/opt/PhantomBot_data
    environment:
      PHANTOMBOT_USER: "bluepandaphantom"
      PHANTOMBOT_CHANNEL: "jenthebluepanda"
      PHANTOMBOT_PANELUSER: "{REDACTED}"
      PHANTOMBOT_PANELPASSWORD: "{REDACTED}"
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_DEBUGON: "true"
```

1) Create a `docker-compose.yml` similar to this one
2) Run `docker-compose up`
3) Observe output that misleads the user to what's actually wrong

Logs:
```
seth@Rogeliina:~/Desktop/docker/phantombot/temp$ docker-compose up
Recreating temp_phantombot_1 ... done
Attaching to temp_phantombot_1
phantombot_1  | [02-03-2021 @ 13:16:05.042 GMT] The working directory is: /opt/PhantomBot
phantombot_1  | [02-03-2021 @ 13:16:05.102 GMT] Detected Java 11.0.4 running on Linux 5.4.0-65-generic (amd64)
phantombot_1  | 
phantombot_1  | Welcome to the PhantomBot setup process!
phantombot_1  | If you have any issues please join our Discord!
phantombot_1  | Discord: https://discord.gg/YKvMd78
phantombot_1  | 
phantombot_1  | PhantomBot has detected that your device is running Linux.
phantombot_1  | Here's the setup guide for Ubuntu: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/ubuntu
phantombot_1  | Here's the setup guide for CentOS: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/centos
phantombot_1  | 
phantombot_1  | 
phantombot_1  | 1. Please enter the bot's Twitch username: [02-03-2021 @ 13:16:05.131 GMT] [ERROR] Failed to setup PhantomBot. Now exiting...
```
