### ISSUE TITLE
When Running via Docker, Deleted Modules Return on Restart

### ISSUE THREAD

**Issue by SethFalco** [PhantomBot/PhantomBot#2448]
PhantomBot Version: 3.4.1 (stable) (Revision: 6d1a942)
Operating System: Linux
Java Version: 11.0.4+10-LTS

Detailed Description:
When running via Docker, the additional modules that aren't desired come back on restart.

Not only do they return, but any of the settings for it that may have been modified before also get undone. For example, if the commands added by a module were disabled, then they enabled again on restart. 

Steps to Reproduce:
```yml
version: "3.8"
services:
  phantombot:
    image: gmt2001/phantombot-stable:3.4.1
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - ./PhantomBot_data:/opt/PhantomBot_data
    environment:
      PHANTOMBOT_USER: "bluepandaphantom"
      PHANTOMBOT_OAUTH: "{REDACTED}"
      PHANTOMBOT_CHANNEL: "jenthebluepanda"
      PHANTOMBOT_PANELUSER: "{REDACTED}"
      PHANTOMBOT_PANELPASSWORD: "{REDACTED}"
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_DEBUGON: "true"
```

1. Run PhantomBot via Docker / Docker Compose. (`docker-compose up -d`)
2. Go to `Settings -> Modules`.
3. Delete one of the modules such as `./games/8ball.js`, the total entries should've dropped by 1.
4. Restart the service. (`docker-compose restart`)
5. Observe the total number of modules, which should return to when no modules were deleted.

I haven't debugged the issue, but I assume it's because the modules are managed inside the container, thus the state of them is lost when the container is stopped. The solution would probably be to allow the folder containing modules to be externalized from the Docker container.
