### ISSUE TITLE
"PhantomBot Update" but on Latest Version

### ISSUE THREAD

**Issue by SethFalco** [PhantomBot/PhantomBot#2458]
PhantomBot Version: PhantomBot Version: 3.4.2 (custom) (Revision: bf69ab8)
O/S Version: Linux (Docker)
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related): Firefox 85.0.1 (64-bit)

Detailed Description:
Every time once accesses the panel, they get a notification that a new version of PhantomBot is available.

> Version v3.4.2 of PhantomBot is now available to download! 

However, I'm already on v3.4.2, so should not be getting this notification. (Especially every time I open the panel. ^-^')

Steps to Reproduce:
**`docker-compose.yml`**
```yml
version: "3.8"
services:
  phantombot:
    image: gmt2001/phantombot-stable:3.4.2
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - PhantomBot_data:/opt/PhantomBot_data
    environment:
      PHANTOMBOT_USER: "bluepandaphantom"
      PHANTOMBOT_OAUTH: "{REDACTED}"
      PHANTOMBOT_CHANNEL: "jenthebluepanda"
      PHANTOMBOT_PANELUSER: "{REDACTED}"
      PHANTOMBOT_PANELPASSWORD: "{REDACTED}"
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_DEBUGON: "true"
volumes:
  PhantomBot_data:
```

1. Go to the panel at `{host}:25000`
2. Observe notification

Screenshots (if applicable):

![image](https://user-images.githubusercontent.com/22801583/109337225-c6110900-7864-11eb-8b2d-94d160477461.png)
