### ISSUE TITLE
Error running the Docker/Docker Compose

### ISSUE THREAD

**Issue by mrcsdl** [PhantomBot/PhantomBot#2496]
PhantomBot Version: phantombot-nightly:latest
O/S Version: debian but trying to run the bot in a docker with docker compose file, 
iam using Portainer for visualisation of all my docker containers.
Java Version: 11.0.4
Web Browser Version (if Panel related): latest

my docker compose file:
version: '3'
services:
  phantombot:
    container_name: phantombot-nightly
    image: gmt2001/phantombot-nightly:latest
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - /home/marc/apps/Bot:/opt/PhantomBot_data
    environment:
      # ------ Override any botlogin.txt variable here, with the PHANTOMBOT_ prefix
      # Twitch bot user (Required)
      PHANTOMBOT_USER: ""
      # Twitch bot user OAuth token (https://phantombot.github.io/PhantomBot/oauth/) (Required)
      PHANTOMBOT_OAUTH: ""
      # Twitch caster channel OAuth token (https://phantombot.github.io/PhantomBot/oauth/)
      PHANTOMBOT_APIOAUTH: ""
      # Twitch caster channel (Required)
      PHANTOMBOT_CHANNEL: ""
      # Webinterface username
      PHANTOMBOT_PANELUSER: ""
      # Webinterface password
      PHANTOMBOT_PANELPASSWORD: ""
      # Webinterface use https?
      PHANTOMBOT_USEHTTPS: "true"

Error Log is attatched.
[_phantombot_logs.txt](https://github.com/PhantomBot/PhantomBot/files/6653282/_phantombot_logs.txt)

**Comment by LyeosMaouli** [comment]
Your issue might be that you are missing the volume creation at the end :
```
volumes:
  PhantomBot_data:
```
So your container didn't create the volume **PhantomBot_data** and tries to access logs in an unkown volume.

This is what your docker-compose.yml should look like : 

```
version: '3'
services:
  phantombot:
    container_name: phantombot-nightly
    image: gmt2001/phantombot-nightly:latest
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - /home/marc/apps/Bot:/opt/PhantomBot_data
    environment:
      # ------ Override any botlogin.txt variable here, with the PHANTOMBOT_ prefix
      # Twitch bot user (Required)
      PHANTOMBOT_USER: ""
      # Twitch bot user OAuth token (https://phantombot.github.io/PhantomBot/oauth/) (Required)
      PHANTOMBOT_OAUTH: ""
      # Twitch caster channel OAuth token (https://phantombot.github.io/PhantomBot/oauth/)
      PHANTOMBOT_APIOAUTH: ""
      # Twitch caster channel (Required)
      PHANTOMBOT_CHANNEL: ""
      # Webinterface username
      PHANTOMBOT_PANELUSER: ""
      # Webinterface password
      PHANTOMBOT_PANELPASSWORD: ""
      # Webinterface use https?
      PHANTOMBOT_USEHTTPS: "true"

volumes:
  PhantomBot_data:
```
