### ISSUE TITLE
Webinterface ist not comming up

### ISSUE THREAD

**Issue by nixmomo** [PhantomBot/PhantomBot#2584]
PhantomBot Version:3.4.7
O/S Version:Docker
Java Version:Docker
Web Browser Version (if Panel related):All Browsers

Detailed Description: Webinterface is not started after Bot is ready message in logs

Steps to Reproduce: Just run
docker compose
```
version: '3.7'

services:
  phantombot:
    image: gmt2001/phantombot-stable:3.4.7
    expose:
      - 25000
      - 25001
      - 25002
      - 25003
      - 25004
    environment:
      PHANTOMBOT_CHANNEL: XXX
      PHANTOMBOT_USER: XXX
      PHANTOMBOT_OAUTH: oauth:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      PHANTOMBOT_PANELSOCKETPORT: 25000
      PHANTOMBOT_PANELUSER: YYYY
      PHANTOMBOT_PANELPASSWORD: XXXX
      PHANTOMBOT_YOUTUBEKEY: xxxxxxxxxxxxx
      PHANTOMBOT_USEHTTPS: 'true'
      PHANTOMBOT_HTTPSPASSWORD: XXXX
      PHANTOMBOT_HTTPSFILENAME: /opt/PhantomBot_data/ssl/bot.jks
      SSL: Test 2

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /phantombot/backup:/backup
      - /phantombot/addons:/opt/PhantomBot_data/addons
      - /phantombot/config:/opt/PhantomBot_data/config
      - /phantombot/dbbackup:/opt/PhantomBot_data/dbbackup
      - /phantombot/logs:/opt/PhantomBot_data/logs
      - /phantombot/ssl/:/opt/PhantomBot_data/ssl
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.role == worker
      resources:
        limits:
          cpus: '0.7'
          memory: 500M

      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.bot-http.rule=Host(`bot.domain.tld`)
        - traefik.http.routers.bot-http.entrypoints=http
        - traefik.http.routers.bot-https.service=bot
        - traefik.http.routers.bot-https.rule=Host(`bot.domain.tld`)
        - traefik.http.routers.bot-https.entrypoints=https
        - traefik.http.routers.bot-https.tls=true
        - traefik.http.routers.bot-https.tls.certresolver=le
        - traefik.http.services.bot.loadbalancer.server.port=25000
        - traefik.http.services.bot.loadbalancer.server.scheme=https
        - traefik.http.services.bot.loadbalancer.passhostheader=true

        
networks:
  traefik-public:
    external: true 
```

Expose the Port directly on Host is not working too... it seems that i miss something to start the internal webserver but i did not found it yet?
My Botlogin.txt
```
musicenable=false
httpspassword=XXX
youtubekey=XXX
channel=XXX
webenable=true
ytauth=XXXX
webauth=XXX
webauthro=TXXXX
panelpassword=XXX
usehttps=true
httpsfilename=/opt/PhantomBot/ssl/bot.jks
oauth=oauth\:XXX
whisperlimit60=60.0
owner=XX
baseport=25000
msglimit30=19.0
ytauthro=XXXX
user=XXX
paneluser=XXX
proxybypasshttps=true
```

Logs:

Screenshots (if applicable):
