### ISSUE TITLE
Containerized Phantombot fails to recognize argued username

### ISSUE THREAD

**Issue by ZAdamMac** [PhantomBot/PhantomBot#2605]
PhantomBot Version: 3.5.0.1 (stable, Docker)
O/S Version: Linux 5.4.0-91-generic (amd64)
Java Version: Detected Java 11.0.11
Web Browser Version (if Panel related): N/A

Detailed Description:

When setting up docker-compose deployment for two phantombots working prior to an update to 3.5.0.1, ran into an issue that required the original volumes to be removed and recreated. I now get a condition where one of the two deployments (patch, in the logs below) fails to recognized that the PHANTOMBOTS_USER value is set (in this case, `al_whizzbang`). The  second bot, `meowkie`, recognizes its settings and starts as normal (minus an expected error about it's oauth token being expired).

Refer to the following docker-compose file.

Note that removing the old volumes and re-creating them is the only change to this setup from its last-known-working configuration.

```yaml
version: '3'

services:
  meowkie:
    restart: always
    image: gmt2001/phantombot-stable:latest
    volumes:
      - meowkieconfig:/opt/PhantomBot_data
    ports:
      - 25002
    environment:
      PHANTOMBOT_USER: "meowkiebot"
      PHANTOMBOT_OAUTH: "[REDACTED]"
      PHANTOMBOT_APIOAUTH: ""
      PHANTOMBOT_BASEPORT: "25002"
      PHANTOMBOT_CHANNEL: "meowkie"
      PHANTOMBOT_PANELUSER: "meowkiebot_admin"
      PHANTOMBOT_PANELPASSWORD: "[REDACTED]"
      PHANTOMBOT_USEHTTPS: "false"
      # Several env vars not used by phantombot redacted

  patch:
    restart: always
    image: gmt2001/phantombot-stable:latest
    volumes:
      - patchconfig:/opt/PhantomBot_data
    ports:
      - 25000
    environment:
      PHANTOMBOT_USER: "al_whizzbang"
      PHANTOMBOT_APIOAUTH: "[REDACTED]"
      PHANTOMBOT_CHANNEL: "patcharcana"
      PHANTOMBOT_PANELUSER: "twitch_whizzbang"
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_PROXYBYPASS: "true"
      # Several env vars not used by phantombot redacted

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  patchconfig:
  meowkieconfig:

```

Steps to Reproduce:
1. create the above docker-compose.yml file somewhere relevant.
2. `docker-compose up`

Logs:

```
adminops@corvus:/var/www/phantombots$ docker-compose up
Creating volume "phantombots_patchconfig" with default driver
Creating volume "phantombots_meowkieconfig" with default driver
Creating phantombots_meowkie_1 ... done                                                                                                                                                                                    Creating phantombots_patch_1   ... done                                                                                                                                                                                    Attaching to phantombots_meowkie_1, phantombots_patch_1
meowkie_1  | [12-01-2021 @ 17:43:51.624 GMT] The working directory is: /opt/PhantomBot
patch_1    | [12-01-2021 @ 17:43:51.691 GMT] The working directory is: /opt/PhantomBot
meowkie_1  | [12-01-2021 @ 17:43:51.765 GMT] Detected Java 11.0.11 running on Linux 5.4.0-91-generic (amd64)
patch_1    | [12-01-2021 @ 17:43:51.846 GMT] Detected Java 11.0.11 running on Linux 5.4.0-91-generic (amd64)
patch_1    |
patch_1    | Welcome to the PhantomBot setup process!
patch_1    | If you have any issues please join our Discord!
patch_1    | Discord: https://discord.gg/YKvMd78
patch_1    |
patch_1    | PhantomBot has detected that your device is running Linux.
patch_1    | Here's the setup guide for Ubuntu: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/ubuntu
patch_1    | Here's the setup guide for CentOS: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/centos
patch_1    |
patch_1    |
meowkie_1  |
meowkie_1  | [12-01-2021 @ 17:43:52.076 GMT] Sending exceptions to Rollbar
meowkie_1  | [12-01-2021 @ 17:43:52.076 GMT] You can disable this by adding the following to a new line in botlogin.txt and restarting: userollbar=false
meowkie_1  | [12-01-2021 @ 17:43:52.077 GMT] If you got this from the official PhantomBot GitHub, you can submit GPDR delete requests to gpdr@phantombot.hopto.org
meowkie_1  |
meowkie_1  | [12-01-2021 @ 17:43:52.079 GMT]
meowkie_1  | [12-01-2021 @ 17:43:52.133 GMT] PhantomBot Version: 3.5.0.1 (stable, Docker)
meowkie_1  | [12-01-2021 @ 17:43:52.134 GMT] Build Revision: 6e2bfcc
meowkie_1  | [12-01-2021 @ 17:43:52.135 GMT] Creator: mast3rplan
meowkie_1  | [12-01-2021 @ 17:43:52.135 GMT] Developers: gmt2001, Kojitsari, ScaniaTV, & IllusionaryOne
meowkie_1  | [12-01-2021 @ 17:43:52.136 GMT] https://phantombot.github.io/PhantomBot/
meowkie_1  | [12-01-2021 @ 17:43:52.136 GMT]
patch_1    | 1. Please enter the bot's Twitch username: [12-01-2021 @ 17:43:52.138 GMT] [ERROR] Failed to setup PhantomBot. Now exiting...
meowkie_1  | [12-01-2021 @ 17:43:53.968 GMT] [ERROR] [run()@TwitchValidate.java:446] Twitch reports your CHAT (oauth) OAUTH token as invalid. It may have expired, been disabled, or the Twitch API is experiencing issues.
meowkie_1  | [12-01-2021 @ 17:43:53.984 GMT] [WARN] [checkOAuthInconsistencies()@TwitchValidate.java:382] CHAT (oauth) does not have chat:edit. Bot may be unable to respond
meowkie_1  | [12-01-2021 @ 17:43:53.988 GMT] [WARN] [checkOAuthInconsistencies()@TwitchValidate.java:390] CHAT (oauth) is not logged in as meowkiebot. OAuth token may be under the wrong login
meowkie_1  |
meowkie_1  | [12-01-2021 @ 17:43:54.804 GMT] [WARN] [<init>()@PhantomBot.java:588] OAuth was invalid, not starting TMI (Chat)
meowkie_1  | [12-01-2021 @ 17:43:54.806 GMT] [WARN] [<init>()@PhantomBot.java:589] Please go the the bots built-in oauth page and setup a new Bot (Chat) token
meowkie_1  | [12-01-2021 @ 17:43:54.808 GMT] [WARN] [<init>()@PhantomBot.java:590] The default URL is http://localhost:25000/oauth/
meowkie_1  | [12-01-2021 @ 17:43:54.808 GMT] [WARN] [<init>()@PhantomBot.java:591] Please restart the bot after setting up OAuth
meowkie_1  |
patch_1    | [12-01-2021 @ 17:43:55.069 GMT] The working directory is: /opt/PhantomBot
patch_1    | [12-01-2021 @ 17:43:55.226 GMT] Detected Java 11.0.11 running on Linux 5.4.0-91-generic (amd64)
patch_1    |
patch_1    | Welcome to the PhantomBot setup process!
patch_1    | If you have any issues please join our Discord!
patch_1    | Discord: https://discord.gg/YKvMd78
patch_1    |
patch_1    | PhantomBot has detected that your device is running Linux.
patch_1    | Here's the setup guide for Ubuntu: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/ubuntu
patch_1    | Here's the setup guide for CentOS: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/centos
patch_1    |
patch_1    |
patch_1    | 1. Please enter the bot's Twitch username: [12-01-2021 @ 17:43:55.459 GMT] [ERROR] Failed to setup PhantomBot. Now exiting...
```
