### ISSUE TITLE
Docker Install behind traefik with Audio Hook issue

### ISSUE THREAD

**Issue by bnoffer** [PhantomBot/PhantomBot#2622]
PhantomBot Version: 3.5.0.2-NB-12102021 (nightly_build, Docker) (Revision: 23f1b6d)
O/S Version: Linux/Docker
Java Version: 11.0.8+10
Web Browser Version (if Panel related): Firefox 95.0 on macOS 12.0.1

Detailed Description:
I installed Phantom Bot via the nightly docker image and am using the traefik reverse proxy. The bot works so far, integration with Twitch worked out fine. However trying to test the Audio Hooks seems not to work.

However I recognized that the UI is giving me a wrong url for the Browser Source:
http://phantombot.mydomain.tld:443/alerts?allow-audio-hooks=true&allow-alerts=false&audio-hook-volume=0.8
instead of:
https://phantombot.mydomain.tld/alerts?allow-audio-hooks=true&allow-alerts=false&audio-hook-volume=0.8

Browser permissions etc. work fine and I have the same issue within OBS.

Steps to Reproduce:
Here is my docker-compose.yml for reference:
```
version: '3'
services:
  phantombot:
    container_name: phantombot-nightly
    image: gmt2001/phantombot-nightly:latest
    hostname: phantombot.mydomain.tld
    networks:
       - proxy
    restart: always
    volumes:
      - PhantomBot_data:/opt/PhantomBot_data
    environment:
      # ------ Override any botlogin.txt variable here, with the PHANTOMBOT_ prefix
      # Twitch bot user (Required)
      PHANTOMBOT_USER: ""
      # Twitch bot user OAuth token (https://phantombot.github.io/PhantomBot/oauth/) (Required)
      PHANTOMBOT_OAUTH: ""
      # Twitch caster channel OAuth token (https://phantombot.github.io/PhantomBot/oauth/)
      PHANTOMBOT_APIOAUTH: ""
      # Twitch caster channel (Required)
      PHANTOMBOT_CHANNEL: ""
      # Webinterface username
      PHANTOMBOT_PANELUSER: ""
      # Webinterface password
      PHANTOMBOT_PANELPASSWORD: ""
      # Webinterface use https?
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_PROXYBYPASSHTTPS: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phantombot.entrypoints=http"
      - "traefik.http.routers.phantombot.rule=Host(`phantombot.mydomain.tld`)"
      - "traefik.http.routers.phantombot.tls=true"
      - "traefik.http.routers.phantombot.tls.certresolver=myresolver"
      - "traefik.http.routers.phantombot.tls.domains[0].main=phantombot.mydomain.tld"
      - "traefik.http.middlewares.phantombot-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phantombot.middlewares=phantombot-https-redirect"
      - "traefik.http.routers.phantombot-secure.entrypoints=https"
      - "traefik.http.routers.phantombot-secure.rule=Host(`phantombot.mydomain.tld`)"
      - "traefik.http.routers.phantombot-secure.tls=true"
      - "traefik.http.routers.phantombot-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.phantombot-secure.service=phantombot"
      - "traefik.http.services.phantombot.loadbalancer.server.port=25000"
      - "traefik.docker.network=proxy"

volumes:
  PhantomBot_data:
networks:
  proxy:
    external: true
```
Credentials and real domains have of course been removed.

Logs:
Logs have no information on this.

Screenshots (if applicable):
