### ISSUE TITLE
Unable to connect to PhantomBot web UI (ws reconnects)

### ISSUE THREAD

**Issue by kriakiku** [PhantomBot/PhantomBot#3543]
**PhantomBot Version:** v3.14.0.6
**O/S Version:** umbrelOS 1.2.2
**Java Version:** -
**Web Browser Version (if Panel related):** Chrome latest

**Detailed Description:**
I’m trying to run PhantomBot via Docker on one of my computers running UmbrelOS, but when I try to access the web panel after logging in, I get infinite reconnections to the websocket. I tried accessing it through the local domain (umbrel.local) and the internal IP address, but nothing helps.

**Steps to Reproduce:**

Docker Compose file:

```
services:
  server:
    image: ghcr.io/phantombot/phantombot
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/opt/PhantomBot_data
    extra_hosts:
      - umbrel.local:127.0.0.1
    ports:
      - target: 25000
        published: 25000
        protocol: tcp
    environment:
      PHANTOMBOT_ENVOVERRIDE: true
      PHANTOMBOT_USEHTTPS: false

      PHANTOMBOT_DEBUGON: true
      PHANTOMBOT_DEBUGLOG: true
      PHANTOMBOT_IRCDEBUG: true
      PHANTOMBOT_HELIXDEBUG: true
      PHANTOMBOT_WSDEBUG: true
      PHANTOMBOT_REACTORDEBUG: true
      PHANTOMBOT_INTERNALDEBUG: true
      PHANTOMBOT_WSPINGERDEBUG: true
      PHANTOMBOT_EVENTSUBDEBUG: true
      PHANTOMBOT_DNSDEBUG: true
      PHANTOMBOT_HTTPCLIENTDEBUG: true
      PHANTOMBOT_PATHVALIDATEDEBUG: true
      PHANTOMBOT_RHINODEBUGGER: true

      PHANTOMBOT_PANELUSER: umbrel
      PHANTOMBOT_PANELPASSWORD: $APP_PASSWORD
      PHANTOMBOT_USEDEFAULTDNSRESOLVER: true
```

Logs:

```
[...]
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:44 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameEncoder encode
kriakiku-phantombot_server_1  | FINEST: Encoding WebSocket Frame opCode=8 length=23
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker handshake
kriakiku-phantombot_server_1  | FINE: [id: 0x86fb66c6, L:/10.21.0.34:25000 - R:/192.168.68.127:61794] WebSocket version V13 server handshake
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker13 newHandshakeResponse
kriakiku-phantombot_server_1  | FINE: WebSocket version 13 server handshake key: Ce1Q+JOZaJUsbEilqeGtag==, response: njA/FMZwx1MGsDcjJin1oJL+P1E=
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder decode
kriakiku-phantombot_server_1  | FINEST: Decoding WebSocket Frame opCode=1
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder decode
kriakiku-phantombot_server_1  | FINEST: Decoding WebSocket Frame length=64
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameEncoder encode
kriakiku-phantombot_server_1  | FINEST: Encoding WebSocket Frame opCode=1 length=37
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder decode
kriakiku-phantombot_server_1  | FINEST: Decoding WebSocket Frame opCode=1
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder decode
kriakiku-phantombot_server_1  | FINEST: Decoding WebSocket Frame length=58
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:45 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameEncoder encode
kriakiku-phantombot_server_1  | FINEST: Encoding WebSocket Frame opCode=8 length=23
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:46 AM io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker handshake
kriakiku-phantombot_server_1  | FINE: [id: 0x97ae8303, L:/10.21.0.34:25000 - R:/192.168.68.127:61799] WebSocket version V13 server handshake
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:46 AM io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker13 newHandshakeResponse
kriakiku-phantombot_server_1  | FINE: WebSocket version 13 server handshake key: UQqN9x93nOZuiyO4rIRwmA==, response: UISjwQ0v88uBwjDx6NaQZLvKqBs=
kriakiku-phantombot_server_1  | Oct 01, 2024 8:04:46 AM io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder decode
[...]
```

**Screenshots (if applicable):**

![Снимок экрана 2024-10-01 в 13 09 41](https://github.com/user-attachments/assets/b2c0f6b2-ed74-4933-90b3-d168c17ae639)

![Снимок экрана 2024-10-01 в 13 10 12](https://github.com/user-attachments/assets/9c16d50b-6f09-4d3f-84a3-a343526becf6)
